paths:
    jquery: "jquery/jquery"
    underscore: "underscore/underscore"
    backbone: "backbone/backbone"
    "jquery-mobile": "jquery-mobile-bower/js/jquery.mobile-1.4.2.min"
    tpl: "requirejs-tpl/tpl"
    "backbone-query-parameters": "backbone-query-parameters/backbone.queryparams"
    "backbone-query-parameters-shim": "backbone-query-parameters/backbone.queryparams-1.1-shim"
    serializeJSON: "jquery.serializeJSON/jquery.serializejson"
    "jqm-config": "jqm-config"
    fastclick: "fastclick/lib/fastclick"

shim:
    "backbone-query-parameters":
        deps: ['backbone-query-parameters-shim']
    'backbone':
        deps: ['backbone-query-parameters-shim']
    'jqm-config':
        deps: ["jquery-mobile"]

modules:
  - name: 'application' # default

tpl:
    extension: '.html' # default
