paths:
    'jquery': "http://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.3/zepto.min"
    'underscore': "http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min"
    'backbone': "http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min"
    'tpl': "http://cdnjs.cloudflare.com/ajax/libs/requirejs-tpl/0.0.2/tpl"
    'fastclick': "http://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.0/fastclick.min"
    'async': "http://cdnjs.cloudflare.com/ajax/libs/requirejs-async/0.1.1/async"
    'text': "http://cdnjs.cloudflare.com/ajax/libs/require-text/2.0.10/text"
    'ratchet': 'http://cdnjs.cloudflare.com/ajax/libs/ratchet/2.0.2/js/ratchet.min'
shim:
    'jquery':
        exports: '$'
    'underscore':
        exports: '_'
    'backbone':
        deps: ['jquery', 'underscore']
        exports: 'Backbone'

modules:
  - name: 'application' # default

tpl:
    extension: '.html' # default
